version: '3.8'

services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'   # HTTP traffic
      - '8081:81'   # Admin interface
      - '443:443' # HTTPS traffic
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt 
    networks:
      - nginx-network 
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  nginx-network:
    driver: bridge
    name: nginx 